from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CHECKS = ROOT / "01_Plans" / "docs_contract_checks.py"
TESTS = ROOT / "01_Plans" / "tests" / "test_docs_contract_checks.py"
ISSUE = ROOT / "01_Plans" / "issues" / "done" / "issue-DOC-CI-DRIFT-01-docs-check-optional-workflow-paths.md"

checks = CHECKS.read_text(encoding="utf-8")
old = '''def check_ci_job_timeouts(\n    root: Path,\n    workflow_paths: tuple[Path, ...] = CI_WORKFLOW_PATHS,\n) -> list[DocsCheckFinding]:\n    \"\"\"Require every job in the maintained GitHub Actions workflows to have a bounded timeout.\"\"\"\n    findings: list[DocsCheckFinding] = []\n    for relative_path in workflow_paths:\n        source = root / relative_path\n        lines = source.read_text(encoding=\"utf-8\").splitlines()\n'''
new = '''def check_ci_job_timeouts(\n    root: Path,\n    workflow_paths: tuple[Path, ...] = CI_WORKFLOW_PATHS,\n) -> list[DocsCheckFinding]:\n    \"\"\"Require bounded timeouts in each maintained workflow that exists.\n\n    A configured path is a workflow to inspect when present, not a requirement\n    that GitHub Actions itself be enabled. Repositories or revisions that do not\n    carry one of these workflow files therefore have no jobs for this rule to\n    inspect.\n    \"\"\"\n    findings: list[DocsCheckFinding] = []\n    for relative_path in workflow_paths:\n        source = root / relative_path\n        if not source.is_file():\n            continue\n        lines = source.read_text(encoding=\"utf-8\").splitlines()\n'''
if old not in checks:
    raise SystemExit("check_ci_job_timeouts anchor not found")
CHECKS.write_text(checks.replace(old, new, 1), encoding="utf-8")

tests = TESTS.read_text(encoding="utf-8")
marker = '''    def test_accepts_bounded_timeout_for_every_job(self):\n        with tempfile.TemporaryDirectory() as td:\n            root = Path(td)\n            workflow = root / \"workflow.yml\"\n            workflow.write_text(\n                \"jobs:\\n\"\n                \"  first-job:\\n\"\n                \"    timeout-minutes: 5\\n\"\n                \"  second_job:\\n\"\n                \"    timeout-minutes: 360\\n\",\n                encoding=\"utf-8\",\n            )\n\n            findings = MODULE.check_ci_job_timeouts(root, (Path(\"workflow.yml\"),))\n\n        self.assertEqual(findings, [])\n'''
addition = marker + '''\n    def test_ignores_configured_workflow_paths_that_do_not_exist(self):\n        with tempfile.TemporaryDirectory() as td:\n            root = Path(td)\n\n            findings = MODULE.check_ci_job_timeouts(\n                root,\n                (Path(\".github/workflows/ci.yml\"), Path(\".github/workflows/release.yml\")),\n            )\n\n        self.assertEqual(findings, [])\n'''
if marker not in tests:
    raise SystemExit("CiJobTimeoutCheckTest anchor not found")
TESTS.write_text(tests.replace(marker, addition, 1), encoding="utf-8")

ISSUE.write_text('''# Issue: DOC-CI-DRIFT-01 GitHub Actionsを使わない構成でもdocs-checkを単体実行できるようにする\n\n- Type: Test / Process\n- Status: Done\n- Source Issue: COGNITIVE-DOGFOOD-01\n- Priority: P1\n- Owner: Maintainer\n- Scope: `01_Plans/docs_contract_checks.py`, `01_Plans/tests/test_docs_contract_checks.py`\n- Related ADR/Spec: `01_Plans/documentation_quality.md`, `AGENTS.md`\n- Expected verification level: `docs-check`\n\n## 課題\n\n`POST /ai/suggest-island-summary` のLLM入力IR移行を検証した際、現行 `main` で `python 01_Plans/docs_check.py` を実行すると、存在しない `.github/workflows/ci.yml` の読み込みで初期化に失敗することを確認した。\n\n`DC-CI-001` の目的は、リポジトリで維持しているGitHub Actions workflowに無制限実行のjobを残さないことである。一方、現在のリポジトリはGitHub Actions workflowを常設していない。workflowを使わない構成そのものを `DC-CI-001` が禁止しているわけではないため、固定パスが存在しないことを例外として扱うのは検査の責務を越えていた。\n\nこの状態では、GitHub Actionsを再導入しない限り文書契約検査全体を単体実行できず、AI入力IRのような別変更の検証まで妨げる。\n\n## 対応\n\n`check_ci_job_timeouts()` は、設定済みのworkflowパスが実在する場合だけ、その中の各jobに `timeout-minutes` があることを検査する。パスが存在しない場合は「検査対象となるjobがない」として処理を続行する。\n\n既存workflowが存在する場合のfail-closed挙動は変更しない。timeoutがないjob、0分、360分を超える値は従来どおり `DC-CI-001` の違反とする。\n\n## 受入条件\n\n- [x] `.github/workflows/ci.yml` と `.github/workflows/release.yml` が存在しない構成でも `check_ci_job_timeouts()` が例外を送出しない。\n- [x] 実在するworkflowのjobについては、従来どおり有効な `timeout-minutes` を必須とする。\n- [x] workflowを常設すること自体を新しい要件にしない。\n- [x] `python 01_Plans/docs_check.py` を現行リポジトリで最後まで実行できる。\n- [x] 変更後の文書契約テストが成功する。\n\n## 検証\n\n- `python -m unittest discover -s 01_Plans/tests -p test_docs_contract_checks.py`\n- `python 01_Plans/docs_check.py`\n- `python 01_Plans/triage_actionable_plans.py --check`\n- `git diff --check`\n\n## 非目標\n\n- GitHub Actions workflowを常設または再導入すること。\n- `DC-CI-001` のtimeout上限やjob検出規則を変更すること。\n- 別のCI実行基盤の採否を決めること。\n\n## 文書品質の仕上げ\n\n原因、検査の責務、変更しない境界を固めた後、意味を変えずに全文を読み直した。GitHub Actionsを使わない現在構成と、workflowが存在する場合のfail-closed検査を混同しない表現へ整えた。\n''', encoding="utf-8")
