import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { createHash, createSign } from "node:crypto";
import path from "node:path";

const frontendRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const repoRoot = path.resolve(frontendRoot, "..", "..");

function parseArgs(argv) {
  const options = {
    outDir: path.resolve(repoRoot, "03_Implement", "deploy", "public"),
    packId: "default",
    title: "Public Pack",
    keyId: "",
  };

  for (let index = 0; index < argv.length; index += 1) {
    const value = argv[index];
    if (value === "--document") {
      options.document = path.resolve(process.cwd(), argv[index + 1]);
      index += 1;
    } else if (value === "--view") {
      options.view = path.resolve(process.cwd(), argv[index + 1]);
      index += 1;
    } else if (value === "--out") {
      options.outDir = path.resolve(process.cwd(), argv[index + 1]);
      index += 1;
    } else if (value === "--pack-id") {
      options.packId = argv[index + 1];
      index += 1;
    } else if (value === "--title") {
      options.title = argv[index + 1];
      index += 1;
    } else if (value === "--signing-key") {
      options.signingKeyPath = path.resolve(process.cwd(), argv[index + 1]);
      index += 1;
    } else if (value === "--key-id") {
      options.keyId = argv[index + 1];
      index += 1;
    }
  }

  if (!options.document) {
    throw new Error("Missing required --document argument");
  }
  if (options.signingKeyPath && !options.keyId) {
    throw new Error("--key-id is required when --signing-key is provided");
  }

  return options;
}

function sha256Hex(content) {
  return createHash("sha256").update(content).digest("hex");
}

async function listFilesRecursively(rootDir, relativeDir = "") {
  const entries = await readdir(path.resolve(rootDir, relativeDir), { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const rel = relativeDir ? `${relativeDir}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...(await listFilesRecursively(rootDir, rel)));
    } else if (entry.isFile()) {
      files.push(rel);
    }
  }
  return files;
}

async function buildIntegrityManifest(outDir) {
  const files = (await listFilesRecursively(outDir))
    .map((rel) => rel.replace(/\\/g, "/"))
    .filter((rel) => rel !== "integrity.json")
    .sort((a, b) => a.localeCompare(b));

  const hashes = [];
  for (const rel of files) {
    const content = await readFile(path.resolve(outDir, rel));
    hashes.push({ path: rel, sha256: sha256Hex(content) });
  }

  return {
    version: "1",
    hashAlgorithm: "sha256",
    generatedAt: new Date().toISOString(),
    files: hashes,
  };
}

async function signManifestPayload(manifest, signingKeyPath, keyId) {
  const signingKeyPem = await readFile(signingKeyPath, "utf-8");
  const payload = JSON.stringify({
    version: manifest.version,
    hashAlgorithm: manifest.hashAlgorithm,
    files: manifest.files,
  });
  const signer = createSign("RSA-SHA256");
  signer.update(payload);
  signer.end();
  return {
    keyId,
    algorithm: "rsa-sha256",
    value: signer.sign(signingKeyPem).toString("base64"),
  };
}

async function run() {
  const options = parseArgs(process.argv.slice(2));
  const distDir = path.resolve(frontendRoot, "dist");
  const packsDir = path.resolve(options.outDir, "packs");

  await rm(options.outDir, { recursive: true, force: true });
  await mkdir(options.outDir, { recursive: true });

  await import("node:child_process").then(({ execFileSync }) => {
    execFileSync("npm", ["run", "build"], {
      cwd: frontendRoot,
      stdio: "inherit",
      env: process.env,
    });
  });

  await cp(path.resolve(distDir, "index.html"), path.resolve(options.outDir, "index.html"));
  await cp(path.resolve(distDir, "assets"), path.resolve(options.outDir, "assets"), { recursive: true });

  await mkdir(packsDir, { recursive: true });

  const documentFileName = `${options.packId}.document.json`;
  await cp(options.document, path.resolve(packsDir, documentFileName));

  let viewFileName;
  if (options.view) {
    viewFileName = `${options.packId}.view.json`;
    await cp(options.view, path.resolve(packsDir, viewFileName));
  }

  const manifest = {
    defaultPackId: options.packId,
    packs: [
      {
        id: options.packId,
        title: options.title,
        documentPath: documentFileName,
        viewPath: viewFileName,
        enforceSafeMode: true,
        readOnly: true,
        visibility: "Public",
      },
    ],
  };

  await writeFile(path.resolve(packsDir, "index.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");

  const readme = [
    "# Static publish artifact",
    "",
    "This directory is generated by `npm run publish:static`.",
    "",
    "- `index.html`: app entry",
    "- `assets/`: hashed static files",
    "- `packs/index.json`: public pack manifest",
    "- `integrity.json`: SHA-256 digest list (+ optional signature)",
    "",
    `Default URL: ./index.html?pack=${encodeURIComponent(options.packId)}&readonly=1`,
  ].join("\n");

  await writeFile(path.resolve(options.outDir, "README.txt"), `${readme}\n`, "utf-8");

  const indexHtmlPath = path.resolve(options.outDir, "index.html");
  const indexHtml = await readFile(indexHtmlPath, "utf-8");
  const redirectScript = `<script>if(!location.search.includes('pack=')){location.replace('./index.html?pack=${encodeURIComponent(options.packId)}&readonly=1');}</script>`;
  await writeFile(indexHtmlPath, indexHtml.replace("<head>", `<head>${redirectScript}`), "utf-8");

  const integrity = await buildIntegrityManifest(options.outDir);
  if (options.signingKeyPath) {
    integrity.signature = await signManifestPayload(integrity, options.signingKeyPath, options.keyId);
  }
  await writeFile(path.resolve(options.outDir, "integrity.json"), `${JSON.stringify(integrity, null, 2)}\n`, "utf-8");

  console.log(`Generated static publish artifact at: ${options.outDir}`);
}

run().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
